### ISSUE TITLE
nodejs example jose.jwtVerify throws JWKSNoMatchingKey

### ISSUE THREAD

**Issue by Olli2** [signicat/sample-express-mle#1]
While implementing signicat FTN identification with Express test environment I noticed the nodejs example doesn't work.

jose.jwtVerify(jws, validationKeys) throws `JWKSNoMatchingKey: no applicable key found in the JSON Web Key Set`

to reproduce:
1. Create web keys with https://mkjwk.org/
Key size: 2048
Key Use: Encryption
Algorithm: RSA-OAEP: RSAES OAEP using default parameters
Key ID: ~SHA-256~ < client_name >

2. Grab the generated Public Key to signicat API client configs
3. Grab the Public and Private Keypair to be used locally
4. Create identification session
5. Get session and use nodejs example to decrypt -> throws `JWKSNoMatchingKey`

**Comment by Olli2** [comment]
user error, the issue was caused due to not entering the client name as the key ID for jwk

**Comment by Olli2** [comment]
Update: used the client name as the Key ID when generating the jwk but the issues still exists.

**Comment by Slettan** [comment]
Hi Olli2,

The API gateway targets the production environment by default. To target the test environment you have two options:
1. Add your access token to the request (`Authorization: Bearer <token>`). The gateway will parse your client ID and route the request to the correct environment.
2. Add the following header to override the environment: `X-Signicat-Environment: Test`

Hope this helps. I'll add this information as a comment in the sample code as well.
